### PR TITLE
clean code for a better PR, adding title and scrolling support

### PR DESCRIPTION
**Pull request by lesion**
please do not consider preview PRs, the code was a bit confusing.
I'm including here all the features I've added with more comments and
a cleaner code so you can easily take a look at changes and choose what you wanna pick:
- title support (double click to change the title, you can still move the window with drag&drop on title)
- scroll bar support (I really needed this, my notes are always so loooong :P)
- link support (this was life changing to me)
- markdown support

stickynotes

thank you for this piece of software ;)

### CODE REVIEW

**Comment by luizpicolo** [comment]
Better PR.

**Comment by luizpicolo** [comment]
@lesion you removed export and import data?

**Comment by lesion** [comment]
no, I did not remove anything but this PR has 2 years and probably inside the original project this functionality has been added in this period, could be?

**Comment by luizpicolo** [comment]
Okay, now i'm understanding. 
I use the version that you added in PR #4 #3 #2 because the features are excellent. 

Thanks and best resguard.

**Comment by KoenduBuf** [comment]
I want to use this application when this PR (well, the functionality of it) is in, any chance that will ever happen still?

**Pull request closed without merging**
